### ISSUE TITLE
The npm package has the .git directory included

### ISSUE THREAD

**Issue by AlvaroMaceda** [cucumber-ltd/value-object.js#20]
When trying to install other packages, npm raises an error and refuses to continue installation:

npm ERR! path ......./node_modules/value-object
npm ERR! code EISGIT
npm ERR! git ....../node_modules/value-object: Appears to be a git repo or submodule.
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

A temporary workaround is to delete the .git repository existing into the node-modules/value-object repository.

Tested with:
npm version 6.4.1
value-object version: 0.4.1

**Comment by joshski** [comment]
Thanks @AlvaroMaceda!

This is fixed in `0.4.3`
